######################################################################
# Automatically generated by qmake (2.01a) Mi. Mär 12 23:16:15 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/mainwindow.h include/server.h
SOURCES += src/mainwindow.cpp src/server.cpp
